name: Build-And-Run-Tests
run-name: ${{github.actor}} is Running Build And Run Tests
on: [push]
jobs:
    Build-And-Test:
        runs-on: windows-latest
        steps:
            - name: Checkout the repo
            uses: actions/checkout@v4

            -name: Setup CMake
            uses: threeal/cmake-action@v1.3.0

            -name: Build
            runs: cmake --build build

            -name: Test
            runs: ctest --test-dir build -C Debug
            
