name: Link Validation

run-name: "${{github.actor}}: ${{github.event.head_commit.message}}"

on:
    push:
        paths:
        - '**.md'
        - '**/LinkValidation.yml'
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - "main"
            
        paths-ignore:
        - '**.md'
        - '**/LinkValidation.yml'
jobs:
    LinkValidator:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Run linkspector
          uses: umbrelladocs/action-linkspector@v1.1.3
          with:
            fail_on_error: true
