name: Link Validation

run-name: "${{github.actor}}: ${{github.event.head_commit.message}}"

on:
    push:
        paths:
        - '**.md'
        - '**/LinkValidation.yml'
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - "main"
            
        paths-ignore:
        - '**.md'
        - '**/LinkValidation.yml'
jobs:
    LinkValidator:
        runs-on: ubuntu-latest
        steps:
        - run: echo "This job no longer does anything"
