name: Link Validation

run-name: "${{github.actor}}: ${{github.event.head_commit.message}}"

on:
    push:
        paths:
        - '**.md'
        - '**/LinkValidation.yml'
jobs:
    Link Validator:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - uses: gaurav-nelson/github-action-markdown-link-check@v1
