name: Example Repo

run-name: "${{github.actor}}: Run Example repo tests after push to main: ${{github.event.head_commit.message}}"

on:
    push:
        branches:
            - "TriggerActionInExampleRepo"
        
jobs:
    RunExampleWorkflow:
        runs-on: ubuntu-latest
        steps:
        - name: Logging
          run: |
            echo "${{github.event.head_commit.message}}"

        - uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.DISPATCHEXAMPLEWORKFLOWPAT }}
            script: >-
                await github.rest.actions.createWorkflowDispatch({
                    owner: 'KStocky',
                    repo: 'ShaderTestFrameworkExamples',
                    workflow_id: 'BuildAndRunTests.yml',
                    ref: 'main',
                    inputs: {
                        actor: '${{github.actor}}',
                        repository: '${{github.event.repository.name}}',
                        message: 'Merging pull request'
                    }
                })  