name: Example Repo

run-name: "${{github.actor}}: Run Example repo tests for pull request: ${{github.event.pull_request.title}}"

on:
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
          - "main"
        


jobs:
    RunExampleWorkflow:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.DISPATCHEXAMPLEWORKFLOWPAT }}
            script: |
                await github.rest.actions.createWorkflowDispatch({
                    owner: 'KStocky',
                    repo: 'ShaderTestFrameworkExamples',
                    workflow_id: 'BuildAndRunTests.yml',
                    ref: 'main',
                    inputs: {
                        actor: '${{github.actor}}',
                        repository: '${{github.event.repository.name}}',
                        message: '${{github.event.head_commit.message}}'
                    }
                })  