name: Link Validation

on:
    workflow_call:
  
jobs:
    LinkValidator:

        name: Validate Links
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run linkspector
              uses: umbrelladocs/action-linkspector@v1.2.4
              with:
                fail_on_error: true
                filter_mode: nofilter
                config_file: './.linkspector.yml'
