name: Test Compiler Support

run-name: "${{github.actor}}: ${{github.event.head_commit.message || github.event.pull_request.title}}"

on:
  workflow_dispatch:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '**TestCompilerSupport.yml'

  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - "main"
      
    paths-ignore:
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '**TestCompilerSupport.yml'


jobs:
  Test-Compiler-Support:

    runs-on: windows-latest

    env:
        MSVC_VERSION: 14.37
        VS_VERSION: 17.7

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: List VS installations
        shell: cmd
        run: dir "C:\Program Files\Microsoft Visual Studio"

      - name: List VS 2022 installations
        shell: cmd
        run: dir "C:\Program Files\Microsoft Visual Studio\2022"

      - name: List MSVC versions before
        shell: cmd
        run: dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"

      - name: Install MSVC ${{env.MSVC_VERSION}}
        shell: powershell
        run: |
                Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
                $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
                $componentsToAdd= @(
                  "Microsoft.VisualStudio.Component.VC.${{env.MSVC_VERSION}}.${{env.VS_VERSION}}.x86.x64"
                )
                [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
                $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
                # should be run twice
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      #  shell: cmd
      #  run: |
      #      call "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --quiet --norestart --nocache --add Microsoft.VisualStudio.Component.VC.${{env.MSVC_VERSION}}.${{env.VS_VERSION}}.x86.x64
      
      - name: List MSVC versions after
        shell: cmd
        run: dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
      
      - name: Setup Environment to use MSVC ${{env.MSVC_VERSION}}
        uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
        with:
            arch: amd64
            toolset: ${{env.MSVC_VERSION}}
      
      - name: Build with ${{env.MSVC_VERSION}}
        run: cmake --workflow --preset BuildCI
          
            
