name: Test Compiler Support

run-name: "${{github.actor}}: ${{github.event.head_commit.message || github.event.pull_request.title}}"

on:
  workflow_dispatch:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '**TestCompilerSupport.yml'

  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - "main"
      
    paths-ignore:
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '**TestCompilerSupport.yml'
jobs:
  Test-Compiler-Support:

    runs-on: windows-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install MSVC 14.37
        uses: thepwrtank18/install-vs-components@v1.0.0
        with:
            components: Microsoft.VisualStudio.Component.VC.14.37.17.7.x86.x64

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup Environment to use MSVC 14.37
        uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
            arch: x64
            toolset_version: 14.37

      - name: Build with 14.37
        run: cmake --workflow --preset BuildCI
          
            
