name: Test Compiler Support

run-name: "${{github.actor}}: ${{github.event.head_commit.message || github.event.pull_request.title}}"

on:
  workflow_dispatch:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '**TestCompilerSupport.yml'

  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - "main"
      
    paths-ignore:
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '**TestCompilerSupport.yml'


jobs:
  Test-Compiler-Support:

    runs-on: windows-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: List VS installations
        shell: cmd
        run: dir "C:\Program Files\Microsoft Visual Studio"

      - name: List VS 2022 installations
        shell: cmd
        run: dir "C:\Program Files\Microsoft Visual Studio\2022"

      - name: List MSVC versions before
        shell: cmd
        run: dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"

      - name: Install MSVC 14.37
        shell: cmd
        run: call "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --quiet --norestart --nocache --add Microsoft.VisualStudio.Component.VC.14.37.17.7.x86.x64
      
      - name: List MSVC versions after
        shell: cmd
        run: dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
      
      #- name: Setup Environment to use MSVC 14.37
      #  uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
      #  with:
      #      arch: amd64
      #      toolset: 14.37
      #
      #- name: Build with 14.37
      #  run: cmake --workflow --preset BuildCI
          
            
